// Copyright © 2026 Michael Shields
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build windows

package walkui

import (
	"github.com/tailscale/walk"

	"msrl.dev/mink-lasso/internal/ui/model"
)

// appIconResourceName is the RT_GROUP_ICON name build/winres.json embeds
// into the executable (see rsrc_windows_amd64.syso, generated by `make
// winres`).
const appIconResourceName = "APP"

// buildTray creates the tray icon, its context menu, and its mouse
// handling. A failure to load the executable's icon is logged and the tray
// icon is shown without one rather than failing the whole window.
func (b *binding) buildTray(opts Options) error {
	notify, err := walk.NewNotifyIcon()
	if err != nil {
		return err
	}

	b.notify = notify

	if icon, iconErr := walk.NewIconFromResource(appIconResourceName); iconErr != nil {
		b.logger.Warn("load tray icon", "error", iconErr)
	} else if setErr := notify.SetIcon(icon); setErr != nil {
		b.logger.Warn("set tray icon", "error", setErr)
	}

	if err := notify.SetToolTip(opts.Model.TrayTooltip()); err != nil {
		b.logger.Warn("set tray tooltip", "error", err)
	}

	showAction := walk.NewAction()
	if err := showAction.SetText("Show"); err != nil {
		return err
	}

	showAction.Triggered().Attach(b.showAndActivate)

	exitAction := walk.NewAction()
	if err := exitAction.SetText("Exit"); err != nil {
		return err
	}

	exitAction.Triggered().Attach(b.requestExit)

	menu := notify.ContextMenu()
	if err := menu.Actions().Add(showAction); err != nil {
		return err
	}

	if err := menu.Actions().Add(exitAction); err != nil {
		return err
	}

	notify.MouseDown().Attach(func(_, _ int, button walk.MouseButton) {
		if button == walk.LeftButton {
			b.showAndActivate()
		}
	})

	return notify.SetVisible(true)
}

func (b *binding) disposeTray() {
	if b.notify == nil {
		return
	}

	if err := b.notify.Dispose(); err != nil {
		b.logger.Warn("dispose tray icon", "error", err)
	}
}

func (b *binding) paintTrayTooltip() {
	if b.notify == nil {
		return
	}

	if err := b.notify.SetToolTip(b.model.TrayTooltip()); err != nil {
		b.logger.Warn("set tray tooltip", "error", err)
	}
}

func (b *binding) paintBalloon(balloon *model.Balloon) {
	if b.notify == nil {
		return
	}

	var err error

	switch balloon.Kind {
	case model.BalloonError:
		err = b.notify.ShowError(balloon.Title, balloon.Text)
	default:
		err = b.notify.ShowInfo(balloon.Title, balloon.Text)
	}

	if err != nil {
		b.logger.Warn("show tray balloon", "error", err)
	}
}
